source "${ZDOTDIR}/core/zinit.zsh"
source "${ZDOTDIR}/core/functions.zsh"
source "${ZDOTDIR}/core/aliases.zsh"
source "${ZDOTDIR}/core/history.zsh"

plugin "starship"
plugin "zsh-completions"
plugin "zsh-syntax-highlighting"
plugin "zsh-autosuggestions"
